# .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0  # Use the latest tag from https://github.com/pre-commit/pre-commit-hooks/releases
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
- repo: https://github.com/psf/black
  rev: 23.1.0  # Use the latest tag from https://github.com/psf/black/releases
  hooks:
    - id: black
      language_version: python3.11  # Adjust if you use a different Python version
      args: ['--line-length=79']  # Ensure Black uses the same line length as flake8

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0  # Use the latest tag from https://github.com/PyCQA/flake8/releases
  hooks:
    - id: flake8
